---
title: "RcppMeCab bench using Japanese MeCab"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = "styler",
  collapse = TRUE,
  comment = "#>"
)
```

```{r download_corpus}
corp <- quanteda.corpora::download("data_corpus_foreignaffairscommittee")
text <- tail(quanteda::texts(corp), 100)
long_text <- paste0(text[1:50], collapse = "")

remove(corp)

dplyr::glimpse(text)
```

## pos

### String

```{r pos_string_1}
tm <- microbenchmark::microbenchmark(
  pos_join_true = RcppMeCab::pos(text[1], join = TRUE),
  pos_join_false = RcppMeCab::pos(text[1], join = FALSE),
  pos_df = RcppMeCab::pos(text[1], format = "data.frame"),
  times = 50L
)

summary(tm)
```

```{r pos_string_2}
ggplot2::autoplot(tm)
```

### String (Long)

```{r pos_long_1}
tm <- microbenchmark::microbenchmark(
  pos_join_true = RcppMeCab::pos(long_text, join = TRUE),
  pos_join_false = RcppMeCab::pos(long_text, join = FALSE),
  pos_df = RcppMeCab::pos(long_text, format = "data.frame"),
  times = 50L
)

summary(tm)
```

```{r pos_long_2}
ggplot2::autoplot(tm)
```


### Character Vector

```{r pos_vec_1}
tm <- microbenchmark::microbenchmark(
  pos_join_true = RcppMeCab::pos(text, join = TRUE),
  pos_join_false = RcppMeCab::pos(text, join = FALSE),
  pos_df = RcppMeCab::pos(text, format = "data.frame"),
  times = 5L
)

summary(tm)
```

```{r pos_vec_2}
ggplot2::autoplot(tm)
```

## posParallel

### String

```{r pos_parallel_string_1}
tm <- microbenchmark::microbenchmark(
  pos_join_true = RcppMeCab::posParallel(text[1], join = TRUE),
  pos_join_false = RcppMeCab::posParallel(text[1], join = FALSE),
  pos_df = RcppMeCab::posParallel(text[1], format = "data.frame"),
  times = 50L
)

summary(tm)
```

```{r pos_parallel_string_2}
ggplot2::autoplot(tm)
```

### String (Long)

```{r pos_parallel_lon_1}
tm <- microbenchmark::microbenchmark(
  pos_join_true = RcppMeCab::posParallel(long_text, join = TRUE),
  pos_join_false = RcppMeCab::posParallel(long_text, join = FALSE),
  pos_df = RcppMeCab::posParallel(long_text, format = "data.frame"),
  times = 50L
)

summary(tm)
```

```{r pos_parallel_long_2}
ggplot2::autoplot(tm)
```


### Character Vector

```{r pos_parallel_vec_1}
tm <- microbenchmark::microbenchmark(
  pos_join_true = RcppMeCab::posParallel(text, join = TRUE),
  pos_join_false = RcppMeCab::posParallel(text, join = FALSE),
  pos_df = RcppMeCab::posParallel(text, format = "data.frame"),
  times = 5L
)

summary(tm)
```

```{r pos_parallel_vec_2}
ggplot2::autoplot(tm)
```

## sessioninfo

```{r session_info}
sessioninfo::session_info()
```


